// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXZCpmtsi9OvPMrVJZw8flCtH6Sr4aaH0',
    appId: '1:1089857937298:web:d01c2a4d28bb9cb805ab4b',
    messagingSenderId: '1089857937298',
    projectId: 'fasum-apps-f98a1',
    authDomain: 'fasum-apps-f98a1.firebaseapp.com',
    storageBucket: 'fasum-apps-f98a1.firebasestorage.app',
    measurementId: 'G-9KDEL30M6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRibpYMA9z6C-HzurRh5CQnQIu0Hwzxk8',
    appId: '1:1089857937298:android:8d63d06054a47ef105ab4b',
    messagingSenderId: '1089857937298',
    projectId: 'fasum-apps-f98a1',
    storageBucket: 'fasum-apps-f98a1.firebasestorage.app',
  );
}
